scx: Autospec creation for update from version 1.0.8 to version 1.0.9
Alexander Zaitsev (1):
      feat: enable LTO

Andrea Righi (32):
      scx_rustland_core: Fix build warnings
      scx_rustland_core: Select any idle CPU when task affinity changes
      scx_bpfland: support !CONFIG_SMP kernels
      scx_bpfland: never actively wake-up idle CPUs
      scx_bpfland: consider sum_runtime instead of avg_runtime
      scx_bpfland: evaluate deadline based on vruntime and task's sum_vruntime
      scx_bpfland: use nvcsw metrics only for cpufreq scaling
      scx_rusty: prevent scheduling bubbles on kernels >= 6.12
      scx_flash: prevent scheduling bubbles on kernels >= 6.12
      scx_bpfland: do not allow per-CPU kthread to preempt other tasks
      scx_bpfland: proactively wake idle CPUs after task enqueue
      scx_bpfland: fix build warning
      scx_bpfland: do not dispatch per-CPU kthreads directly by default
      scx_bpfland: give queued tasks a chance to run on the same CPU
      scx_bpfland: re-enqueue tasks when a CPU is taken by a higher sched class
      scx_bpfland: avoid starvation of per-CPU tasks
      scx_bpfland: Set max performance level with balance_performance
      scx_bpfland: Avoid updating cpuperf target when not needed
      scx_bpfland: Do not scale slice lag with the task weight
      scx_bpfland: Virtual deadline with partial execution vruntime
      scx_bpfland: Allow tasks to overflow primary domain more aggressively
      scx_bpfland: Get rid of the interactive task classification via nvcsw
      scx_bpfland: Introduce --local-pcpu to prioritize per-CPU tasks
      scx_bpfland: Introduce --cpufreq to enable CPU frequency scaling
      scx_loader: Update performance profiles for scx_bpfland
      scx_bpfland: Mark --local-kthreads/-k as experimental
      scx_rustland_core: remove idle polling
      scx/common.bpf.h: Add helper to check task migration state
      scx_bpfland: enable task preemption
      scx_rustland_core: re-introduce ops.update_idle()
      scx_rustland_core: bump up version to 2.2.6
      scx_utils: Bump up version to 1.0.10

Changwoo Min (41):
      vmlinux: Increase cpumask size in vmlinux.h for all arch
      scx_lavd: Reuse bpf_ktime_get_ns() as many as possible
      scx_lavd: Properly reinitialize cpumask for autopilot mode
      scx_lavd: Turn on frequency scaling in performance mode
      scx_lavd: Add a fast path to pick_idle_cpu() when overloaded
      scx_lavd: Change the default time slice to 5 msec
      scx_lavd: Kick an idle cpu as early as possible on ops.select_cpu()
      scx_lavd: Refactoring lavd_dispatch() for readability
      scx_lavd: Ensure to check all compute domains when task stealing
      scx_lavd: Prioritize a migration-disabled task
      scx_lavd: Add a fast path for a migration-disabled task in pick_idle_cpu()
      sched_ext: Add scx_bpf_now() for BPF scheduler
      sched_ext: Add time helpers for BPF schedulers
      sched_ext: Use time helpers in BPF schedulers
      scx_pair: Remove redundant time_before()
      scx_bpfland: Replace vtime_before() to time_before()
      scx_layered: Replace vtime_before() to time_before()
      scx_mitosis: Replace vtime_before() to time_before()
      scx_rusty: Replace vtime_before() to time_before()
      scx_flash: Replace vtime_before() to time_before()
      scx_pair: Replace bpf_ktime_get_ns() to scx_bpf_now()
      scx_bpfland: Replace bpf_ktime_get_ns() to scx_bpf_now()
      scx_flash: Replace bpf_ktime_get_ns() to scx_bpf_now()
      scx_lavd: Replace bpf_ktime_get_ns() to scx_bpf_now()
      scx_layered: Replace bpf_ktime_get_ns() to scx_bpf_now()
      scx_mitosis: Replace bpf_ktime_get_ns() to scx_bpf_now()
      scx_rusty: Replace bpf_ktime_get_ns() to scx_bpf_now()
      sched_ext: Add description to scx_bpf_now()
      scx_lavd: Use time_delta() for clock difference calculation
      scx_lavd: Optimize have_idle_cpus()
      scx_lavd: Do not reserve an idle cpu at ops.enqueue()
      scx_lavd: Direct dispatch at ops.enqueue()
      scx_lavd: Conder the hardware resource sharing level in CPU ordering
      scx_lavd: Use p->scx.dsq_vtime to store taskc->vdeadline_log_clk
      scx_lavd: Preemption when ops.select_cpu() was skipped
      scx_lavd: Don't try preemption for greedy tasks
      scx_lavd: Do not set task's time slice to zero at the ops.enqueue() path
      scx_lavd: Clean up reset_cpu_preemption_info()
      scx_util: Fix incorrect time delta calculation in time_delta()
      scx_lavd: Revert "scx_lavd: Preemption when ops.select_cpu() was skipped"
      scx_lavd: Use BPF CO-RE for SCX_ENQ_CPU_SELECTED

Daniel Hodges (23):
      docs: Update gentoo installation instructions
      scxtop: Add scxtop tui
      scxtop: Add scheduler view to llc/node views
      scx_layered: Add pid namespace layer matching
      scxtop: Add additional bpf kprobes
      docs: Add scxtop to the developer docs
      scxtop: Refactor bpf event handling and TUI fixes
      scxtop: Add barchart to node view
      scxtop: Add CPU frequency to default sparkline view
      scxtop: Fix attach on newer kernels
      sdt_task: Cleanup formatting
      scxtop: Fix node barchart
      scxtop: Collect uncore frequency
      scxtop: Cleanup event intialization
      scxtop: Add ability to select perf events
      scxtop: Fix scroll on page up
      scxtop: Add event to default list after selection
      scxtop: Fill render area by setting max events
      scxtop: Add scx_stats support
      scxtop: Fix layout for sparklines
      scxtop: Add support for generating perfetto traces
      scxtop: Fix handling non scx scheduled switch events
      scxtop: Add trace options

Daniel Jordan (2):
      scx_prev: a simple scheduler tested on OLTP workloads
      scx_prev: delete unused logic for nr_cpus_allowed == 1 tasks

David Carlier (34):
      scx_utils: addressing few clippy build warnings.
      scx_utils: Fix UserExitInfo::new() usage.
      scx_utils: few code simplifications.
      Revert "scx_utils: Fix UserExitInfo::new() usage."
      disable clippy lint instead.
      move disabling clippy lint in project level
      few code simplifications.
      allow using static mut reference (BUF).
      further little code simplifications.
      code simplifications, using more modern construct when possible.
      scx_rustland_core: fix static mutable reference usage warning (BUF).
      moving it to the related block
      scx_rusty: fix custom PartialOrd implementation build warning.
      load_balance various code simplifications
      rust schedulers: various code simplifications.
      further code simplifications
      scx_central: fix cpu affinity corrupted allocation (glibc).
      scxtop: code simplifications and little optimisation uncore freq file parsing
      scxtop: code simplifications and reduction of heap allocations for perf
      scx_utils: fix gpu-topology build
      scxtop: proposing to add bus-cycles event.
      scxtop: update help display with last changes (perf event scrolling).
      scx_utils/scx_layered: code modernisation/simplifications.
      scx_utils: cleanup gpu topology part
      scx_bpfland: reduce heap allocation with energy profile/primary domain.
      rust schedulers: for sibling cpu using static dispatch instead.
      scx_central: alert for 'silly' values for the chosen cpu from command line.
      remove useless comment
      scxtop: fix short option conflict between tick* options.
      reducing code noise and probes data heap allocation.
      scx_utils: adding cpu affinity data to Gpu type.
      scx_utils: #1281 follow-up for 32 bits.
      scx_utils: addressing #1282 concerns
      scx_layered: various code optimisations/simplifications.

Emil Tsalapatis (78):
      move library include/ directory to sched/include
      scx_rusty: compile with scx library
      bump libbpf-rs to 0.25.0-beta.1 to resolve arena compilation bug
      lib/sdt_task_alloc: factor out common arena allocation code
      lib/sdt_task_alloc: introduce sdt_allocator suballocator
      lib: split between general and task-specific allocation code
      lib/sdt_alloc: rename sdt_task -> sdt_ for non-task specific allocation code
      scx_{rusty, utils}: bump libbpf-rs to 0.25.0-beta.1
      lib: move real header location to scheds/include and fix symlinks
      scx_rusty: compile with the scx standard library
      scx_rusty: remove per-task temp mask and replace with per-CPU singleton
      scx_rusty: use map to manage task masks
      scx_rusty: use arena allocations instead of maps for tasks
      scx_rusty: remove the remaining p <--> tptr conversions
      scx_rusty: add dom_ctx arena
      scx_rusty: allocate domains from arena memory
      lib/sdt_alloc: do not inline allocation loop to prevent verifier instruction limit issues
      lib/sdt_task_alloc: factor out common arena allocation code
      lib/sdt_task_alloc: introduce sdt_allocator suballocator
      lib: split between general and task-specific allocation code
      lib/sdt_alloc: rename sdt_task -> sdt_ for non-task specific allocation code
      reintroduce tptr field in the task-specific allocator
      lib/sdt_alloc: fix LLVM19 compilation error
      scx_utils: emit compilation warning when compiling multiple *.bpf.c files
      scx_layered: fix compilation warnings
      update README
      lib/sdt_alloc: move data allocation out of the critical section
      lib/sdt_alloc: add sleepable pool allocation path
      lib/sdt_alloc: enable the allocation of large structs
      scx_rusty: directly reference domain from task
      scx_rusty: move domain vtime locks to allocator header
      scx_rusty: move per-domain active_tasks queue into arena
      finish moving tasks into arena
      scx_rusty: set default variable value to appease the verifier
      lib/sdt_alloc: enable the allocation of large structs
      arena domains fully operational
      scx_rusty: remove unnecessary variable
      scx_rusty: remove unused domain-to-cpu mapping
      expose dom_ctx arena struct to userspace
      meson: move library dependency to skeleton generator
      meson: do not link lib/ to C schedulers by default
      [WIP] scx_rusty: eagerly migrate tasks between domains
      include: import cond_break definition from the kernel
      lib/sdt_alloc: replace bpf_for loops in critical section with can_loop directive
      scx_rusty: fix compilation warnings for Clang 19
      lib: remove header install step now that headers are in scheds/include
      workarounds for Clang 19 compilation issues
      scx_rusty: export task_ctx structure to userspace
      scx_rusty: rename and eagerly initialize per-cpu temporary CPU masks
      scx_rusty: tag all dom_ctx instances with __arena
      scx_rusty: adjust for Clang 19
      scx_rusty: add explanatory comment on the use of the address_space attribute
      scx_rusty: directly use the domain when adjusting dcycles
      scx_rusty: rename repurposed taskc field from dom_id to target_dom
      scx_rusty: update stale comments
      scx/common.bpf.h: introduce arena-specific READ_ONCE/WRITE_ONCE
      scx_rusty: rename sdt_dom_map_val -> lb_domain
      lib/sdt_alloc: reduce alocation attempts to appease verifier
      scx_rusty: remove stray diagnostic
      scx_rusty: fix formatting
      lib/sdt_alloc: rename sdt_arena_verify to avoid confusion
      typecasts for Clang 18
      make code compatible with both Clang 18 and Clang 19
      scx_rusty: use lb_domain naming for load balancing domains
      scx_rusty: rename and move dom_ctx array
      rename lb_domain_val to lb_domain_get
      remove unused dom_data map
      scx_layered: add command protocol over setname
      scx_layered: add 'join layer' command
      scx_layered: fixes for MATCH_SCXCMD_JOIN
      scx_layered: add example config and code for CMD_JOIN
      scx_rusty: mark create_dom as __weak
      scx_rusty: add option for setting scx_bpf_cpuperf_set()
      sdt_alloc: mark allocation functions as weak
      lib: add typeless arena for static storage allocation
      scx_rusty: rename percpu storage before expanding it
      scx_rusty: initialize static allocator
      lib/sdt_alloc: move sdt_static definition to sdt_task.h header

Fredrik Lönnegren (3):
      scheds: Use crate version for --version
      meson: Install rust projects in tools dir
      docs: Update tumbleweed installation steps

I Hsin Cheng (2):
      scx_flash: Explicitly return in "fexit_vfs_fsync_range"
      scx_flash: Option for userspace lock boosting

Jake Hillion (11):
      bpf_builder: emit warnings from clang
      mitosis: add missing return to select_cpu
      rustland_core: clean up unused functions
      ci: add build-kernel-nix job using dedicated server
      ci: only trigger slack notification on failure of main for scheduled runs
      ci: create reusable workflow for nix kernel builds
      ci: switch scheduled jobs to nix built kernel
      ci: deduplicate rust test jobs and build more targets
      ci: avoid synchronising scheduled jobs
      ci: enable running on github runners when outside of repository
      ci: pass through rust test paths to prevent a rebuild

John Titor (1):
      INSTALL.md: update docs for NixOS

Luigi De Matteis (1):
      ci: disable DEBUG_INFO_REDUCED for arm64

Martin Schaaf (4):
      Crash after wake-up from hibernate: panicked at scheds/rust/scx_bpfland/src/main.rs:615:74
      handle possible error by stats::monitor in scx_layered
      fix lint errors
      fix lint errors

Michal Rostecki (1):
      build: Allow to build bpftool with clang

Misaki Kasumi (10):
      scx_utils: add retries and fallback path for autopower
      Revert "scx_bpfland: do not rely on scx_utils::autopower"
      scx_bpfland & scx_lavd: ppd is not mandatory
      scx_utils: map energy_profile back to power profile
      scx_utils: add SCX_NO_PPD
      scx_utils: add no_ppd arg for fetch_power_profile
      Revert "scx_utils: add SCX_NO_PPD"
      scx_utils: use enum in autopower
      scx_utils: eliminate recursion in autopower
      scx_utils: use debug instead of warn in autopower

Pat Somaru (14):
      add matcher for when tgid is or is not equal to pid
      rename pid_tgid_eq to is_group_leader
      formatting
      misc. lsp cleanup
      scx_layered: add gpu matcher
      add documentation, cleanup cfg name
      set BPF_F_NO_PREALLOC on gpu pid maps
      fix typo in docs
      make ci use a stable branch for MRs etc.
      add hooks to notify when periodic jobs fail
      fix periodic job failure notifications
      fix periodic job failure notifications
      scx_layered: refactor gpu support to workaround nvml issues
      scx_layered: make gpu poll interval configurable

Piotr Gorski (1):
      INSTALL.md: update for openSUSE

Tejun Heo (34):
      Update vmlinux-v6.13-rc1-g353b2a7de2a3.h
      sched_ext: Make cast_mask() inline
      sched_ext: Rename scx_bpf_dispatch[_vtime]() to scx_bpf_dsq_insert[_vtime]()
      sched_ext: Rename scx_bpf_consume() to scx_bpf_dsq_move_to_local()
      sched_ext: Rename scx_bpf_dispatch[_vtime]_from_dsq*() -> scx_bpf_dsq_move[_vtime]*()
      scx/common.bpf.h: Revert formatting changes
      scheds/c: Sync with kernel's tools/sched_ext
      scx/common.h: Make lib/sdt_task.h inclusion optional
      vmlinux.h: Regenerate x86 vmlinux.h and re-enable scx_rusty p->mempolicy optimization
      common.bpf.h: Suppress generated prototypes in vmlinux.h
      scx_layered: Fix lifetime variable related compile warnings
      scx_layered: Clean up open[_preempt] prefixes
      scx_layerd: Separately handle open and grouped layer IDs in Scheduler::init_cpus()
      scx_layered: Split open and grouped layer counts
      scx_layered: Fix open layer handling
      scx_layered: Revive LAYER_USAGE_PROTECTED
      scx_layered: Add disallow_open_after_ns layer attribute
      scx_layered: Implement layer property disallow_preempt_after_us
      scx_layered: Disable owner protection for preempt layers
      scx_layered: Don't apply preempt protection between two open layers
      scx_layered: Improve open layer prot[_preempt] accounting
      scx_layered: Fix multplication overflows
      scx_layered: Fix dump_layer_cpumask()
      scx_layered: Factor out refresh_cpus_flags()
      scx_layered: Implement taskc->cpus_node_aligned
      scx_layered: Implement allow_node_aligned layer property
      scx_layered: Add comment noting subobtimal behavior in layered_select_cpu()
      scx_rusty: Compact ascii diagram at the head of load_balance.rs
      scx_rusty: load_balance: Clean up task_ctx pointer handling
      scx_rusty: load_balance: Derive Debug for Domain and NumaNode
      scx_rusty: Add task_ctx.pid for debug visibility
      scx_rusty: Use bpf_skel::types::* instead of bpf_intf::*
      versions: Synchronize crate versions to the latest used
      versions: Bump versions for v1.0.9 release

likewhatevs (1):
      fix ci

patso (1):
      fix bug in matching logic of tgid==pid matcher

taoky (1):
      scx_loader: Avoid race condition with start_scheduler